"""Assemble the static GitHub Pages site from verified evidence."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _copy(source: Path, destination: Path) -> None:
    if not source.is_file():
        raise FileNotFoundError(f"required site input is missing: {source}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)


def build_site(
    output: Path,
    *,
    hero: Path,
    derby_report: Path,
    backdrop_dir: Path,
) -> list[Path]:
    output = output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    assets = output / "assets"
    copied: list[Path] = []
    for name in ("index.html", "styles.css", "app.js"):
        destination = output / name
        _copy(ROOT / "web" / name, destination)
        copied.append(destination)
    sources = {
        hero: assets / "hero-contact-sheet.png",
        ROOT / "pet" / "spritesheet.webp": assets / "spritesheet.webp",
        backdrop_dir / "overview.png": assets / "backdrop-overview.png",
        backdrop_dir / "report.json": assets / "backdrop-report.json",
        derby_report: assets / "derby-report.json",
    }
    for source, destination in sources.items():
        _copy(source, destination)
        copied.append(destination)
    marker = output / ".goldship-site"
    marker.write_text("Generated by scripts/build_site.py\n", encoding="utf-8", newline="\n")
    copied.append(marker)
    return copied


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "site")
    parser.add_argument(
        "--hero",
        type=Path,
        default=ROOT / "artwork" / "qa" / "contact-sheet.png",
    )
    parser.add_argument(
        "--derby-report",
        type=Path,
        default=ROOT / "build" / "pet-derby" / "report.json",
    )
    parser.add_argument(
        "--backdrop-dir",
        type=Path,
        default=ROOT / "build" / "backdrop-audit",
    )
    args = parser.parse_args()
    try:
        files = build_site(
            args.output,
            hero=args.hero,
            derby_report=args.derby_report,
            backdrop_dir=args.backdrop_dir,
        )
    except OSError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    print(f"PASS: built {len(files)} site files in {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
